app = "aai-risk-api"
primary_region = "iad"

[build]
  dockerfile = "Server/Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]
